<!--Footer Start-->
<div class="b2s-footer">
    <div class="pull-left hidden-xs <?php echo isset($noLegend) ? 'hide' : ''; ?>">
        <small> © <?php echo date('Y'); ?> <a target="_blank" href="http://www.adenion.de" rel="nofollow">Adenion GmbH</a> | <?php _e('We never store your data from your social media profiles.', 'blog2social') ?></small>
    </div>
    <div class="pull-right hidden-xs <?php echo isset($noLegend) ? 'hide' : ''; ?>">
        <small>
            <img class="img-width-9" src="<?php echo plugins_url('/assets/images/b2s/post-icon.png', B2S_PLUGIN_FILE); ?>" alt="beitrag">  <?php _e('Post', 'blog2social') ?> 
            <img class="img-width-9" src="<?php echo plugins_url('/assets/images/b2s/job-icon.png', B2S_PLUGIN_FILE); ?>" alt="job"> <?php _e('Job', 'blog2social') ?>
            <img class="img-width-9" src="<?php echo plugins_url('/assets/images/b2s/event-icon.png', B2S_PLUGIN_FILE); ?>" alt="event"> <?php _e('Event', 'blog2social') ?>
        </small>
    </div>
</div>
<!--Footer Ende-->

<div class="modal fade" id="b2sProFeatureModal" tabindex="-1" role="dialog" aria-labelledby="b2sProFeatureModal" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="b2s-modal-close close" data-modal-name="#b2sProFeatureModal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?php _e('Upgrade to Blog2Social for Premium', 'blog2social') ?></h4>
            </div>
            <div class="modal-body">
                <?php _e('Upgrade to Blog2Social Premium', 'blog2social') ?>
                <br>
                <br>
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Social Media Auto-Posting', 'blog2social') ?><br>
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Post on pages and groups', 'blog2social') ?><br>
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Share on multiple accounts per network', 'blog2social') ?><br>
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Best Time Scheduler: Schedule once, multiple times or recurringly.', 'blog2social') ?><br>  
                <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Reporting with links to all published social media posts', 'blog2social') ?><br>  
                <br>
                <a target="_blank" href="https://service.blog2social.com/" class="btn btn-success center-block"><?php _e('Upgrade to PREMIUM', 'blog2social') ?></a>
                <br>
                <center><?php _e('or <a href="http://service.blog2social.com/trial" target="_blank">start with free 30-days-trial of Blog2Social Premium</a> (no payment information needed)', 'blog2social') ?></center>
            </div>            
        </div>
    </div>
</div>
<div class="modal fade" id="b2sTrailFeedbackModal" tabindex="-1" role="dialog" aria-labelledby="b2sTrailFeedbackModal" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="b2s-modal-close close" data-modal-name="#b2sTrailFeedbackModal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?php _e('Did you miss something?', 'blog2social') ?></h4>
            </div>
            <div class="modal-body">
                <?php _e('Help us make Blog2Social even better!', 'blog2social') ?>
                <textarea id="b2s-trial_message" class="form-control"></textarea>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary b2s-send-trail-feedback"><?php _e('submit', 'blog2social') ?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="b2sInfoSchedTimesModal" tabindex="-1" role="dialog" aria-labelledby="b2sInfoSchedTimesModal" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="b2s-modal-close close" data-modal-name="#b2sInfoSchedTimesModal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?php _e('Best Time Scheduler', 'blog2social') ?></h4>
            </div>
            <div class="modal-body">
                <?php _e('Blog2Social provides you with a ready-to-use best time scheduler based on current research on the <a target="_blank" href="http://www.blog2social.com/en/blog/best-times-to-post-on-social-media/"> best times to post on social media</a>. If you select this option, the calculated time frames will be shown in the scheduling options for each network on the preview below. If you prefer to define your own time settings, you can edit the predefined times or configure your own best time scheduler. In the Blog2Social settings you can define and save your own time settings for all networks. For both options you can always edit the predefined times for single posts or networks or save your new settings as “Your time settings” for future use.', 'blog2social') ?>
                <br>
                <br>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/<?php echo (substr(B2S_LANGUAGE, 0, 2) == 'de' ? 'K8vmGn86Jfg' : 'nY75wI85lco'); ?>" frameborder="0" allowfullscreen></iframe>
                <br>
                <?php if (B2S_PLUGIN_USER_VERSION == 0) { ?>
                    <h4><?php _e('You want to schedule your posts and use the Best Time Scheduler?', 'blog2social'); ?></h4>
                    <?php _e('Upgrade to Blog2Social Premium', 'blog2social') ?>
                    <br>
                    <br>
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Social Media Auto-Posting', 'blog2social') ?><br>
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Post on pages and groups', 'blog2social') ?><br>
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Share on multiple accounts per network', 'blog2social') ?><br>
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Best Time Scheduler: Schedule once, multiple times or recurringly.', 'blog2social') ?><br>  
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Reporting with links to all published social media posts', 'blog2social') ?><br>  
                    <br>
                    <a target="_blank" href="https://service.blog2social.com/" class="btn btn-success center-block"><?php _e('Upgrade to PREMIUM', 'blog2social') ?></a>
                    <br>
                    <center><?php _e('or <a href="http://service.blog2social.com/trial" target="_blank">start with free 30-days-trial of Blog2Social Premium</a> (no payment information needed)', 'blog2social') ?></center>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="b2sInfoLinkModal" tabindex="-1" role="dialog" aria-labelledby="b2sInfoLinkModal" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="b2s-modal-close close" data-modal-name="#b2sInfoLinkModal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?php _e('b2s.pm Link Shortner', 'blog2social') ?></h4>
            </div>
            <div class="modal-body">
                <?php _e('The Blog2Social Shortner converts and publishes your links with a short URL on the social networks.<br>If you choose this option, you avoid that re-shared posts with the same links will be rejected by the networks. The b2s.pm Shortner generates a new link for each social media post. This feature is essential if you wish to re-share your posts on the same networks.Another benefit of the b2s.pm: Shortly, Blog2Social will provide a reporting feature for your social media posts. So, with the b2s.pm links, you will be able to see how often the link has been clicked, liked or shared on your social channels and easily and quickly analyze the performance of your social media posts.<br>You can disable the b2s.pm Shortner to show your original URL.', 'blog2social') ?>
                <br>
            </div>
        </div>
    </div>
</div>




<div class="modal fade" id="b2sInfoAutoShareModal" tabindex="-1" role="dialog" aria-labelledby="b2sInfoAutoShareModal" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?php _e('Blog2Social: Social Media Auto-Posting', 'blog2social') ?><span class="b2s-color-green"><?php _e('(NEW)', 'blog2social') ?></span></h4>
            </div>
            <div class="modal-body">
                <p><?php
                    _e('Blog2Social automatically shares your blog post on your selected social media networks when your post is published. Your selection will be saved and run automatically until changed.', 'blog2social');
                    if (B2S_PLUGIN_USER_VERSION == 0) {
                        ?>
                    <hr>               
                    <h4><?php _e('You want to auto-post your blog post?', 'blog2social'); ?></h4>
                    <?php _e('Upgrade to Blog2Social Premium', 'blog2social') ?>
                    <br>
                    <br>
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Social Media Auto-Posting', 'blog2social') ?><br>
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Post on pages and groups', 'blog2social') ?><br>
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Share on multiple accounts per network', 'blog2social') ?><br>
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Best Time Scheduler: Schedule once, multiple times or recurringly.', 'blog2social') ?><br>  
                    <span class="glyphicon glyphicon-ok glyphicon-success"></span> <?php _e('Reporting with links to all published social media posts', 'blog2social') ?><br>  
                    <br>
                    <a target="_blank" href="https://service.blog2social.com/" class="btn btn-success center-block"><?php _e('Upgrade to PREMIUM', 'blog2social') ?></a>
                    <br>
                    <center><?php _e('or <a href="http://service.blog2social.com/trial" target="_blank">start with free 30-days-trial of Blog2Social Premium</a> (no payment information needed)', 'blog2social') ?></center>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
