<div class="col-md-3 del-padding-left b2s-support-area hidden-xs hidden-sm">
    <?php if (isset($_GET['page']) && $_GET['page'] != 'blog2social-ship' && B2S_PLUGIN_USER_VERSION == 0) { ?>
        <div class="panel panel-default b2s-header-ads-upgrade hidden-xs hidden-sm">
            <div class="panel-body">
                <ul>
                    <li>
                        <a href="https://blog2social.com/<?php echo (substr(B2S_LANGUAGE, 0, 2) == 'en' ? 'en/pricing' : 'de/preise'); ?>" target='_blank'>
                            <img title="B2S Upgrade" alt="B2S Upgrade" class="img-responsive" src="http://service.blog2social.com/ads/images/b2s_ads_upgrade_2016_<?php echo substr(B2S_LANGUAGE, 0, 2); ?>.png">
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    <?php } ?>
    <a target="_blank" href="https://blog2social.com/<?php echo (substr(B2S_LANGUAGE, 0, 2) == 'en' ? 'en/pricing' : 'de/preise'); ?>" class="btn btn-success btn-block"><?php _e('Plans & Pricing', 'blog2social') ?></a>
    <a target="_blank" href="https://service.blog2social.com/<?php echo substr(B2S_LANGUAGE, 0, 2); ?>/support?url=<?php echo get_option('home'); ?>&token=<?php echo B2S_PLUGIN_TOKEN; ?>" class="btn btn-primary btn-block"><?php _e('Support', 'blog2social') ?></a>
    <a target="_blank" href="https://blog2social.com/<?php echo (substr(B2S_LANGUAGE, 0, 2) == 'en' ? 'en/howto' : 'de/anleitung'); ?>" class="btn btn-success btn-block"><?php _e('How to work with Blog2Social', 'blog2social') ?></a>
</div>
